# Generated by Django 6.0 on 2026-01-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='lecturer_latitude',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='lecturer_longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
