# Generated by Django 6.0 on 2026-01-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesession_lecturer_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='lecturer_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='lecturer_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='radius',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
