# Generated by Django 6.0 on 2026-01-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancesession_lecturer_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='session_pin',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
